# Stubs for xeno (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .async_injector import AsyncInjector as AsyncInjector
from .attributes import ClassAttributes as ClassAttributes, MethodAttributes as MethodAttributes, get_injection_params as get_injection_params, get_injection_points as get_injection_points, get_providers as get_providers, scan_methods as scan_methods
from .decorators import alias as alias, const as const, inject as inject, named as named, namespace as namespace, provide as provide, singleton as singleton, using as using
from .errors import CircularDependencyError as CircularDependencyError, ClassInjectionError as ClassInjectionError, InjectionError as InjectionError, InvalidResourceError as InvalidResourceError, MethodInjectionError as MethodInjectionError, MissingDependencyError as MissingDependencyError, MissingResourceError as MissingResourceError, UndefinedNameError as UndefinedNameError, UnknownNamespaceError as UnknownNamespaceError
from .namespaces import Namespace as Namespace
from .sync_injector import SyncInjector as SyncInjector
from .utils import async_map as async_map, async_wrap as async_wrap

Injector = AsyncInjector
