# Stubs for xeno.sync_injector (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .abstract import AbstractInjector
from .attributes import ClassAttributes, MethodAttributes, get_injection_params, get_injection_points
from .decorators import named, singleton
from .errors import ClassInjectionError, MethodInjectionError, MissingDependencyError, MissingResourceError
from .namespaces import Namespace
from .utils import resolve_alias
from typing import Any, Optional

class SyncInjector(AbstractInjector):
    def create(self, class_: Any): ...
    def inject(self, obj: Any, aliases: Any = ..., namespace: str = ...): ...
    def require(self, name: Any, method: Optional[Any] = ...): ...
    def provide(self, name: Any, value: Any, is_singleton: bool = ..., namespace: Optional[Any] = ...): ...
